#server:
#  port: 8082
#
#spring:
#  application:
#    name: demoservice
#  data:
#    mongodb:
#      uri: mongodb+srv://david:HolyDiver@cluster0.aywauo0.mongodb.net/?retryWrites=true&w=majority
#      database: myFirstDatabase
#
#
